# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tony/Desktop/Git/Intrigue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tony/Desktop/Git/Intrigue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tony/Desktop/Git/Intrigue/CMakeFiles /home/tony/Desktop/Git/Intrigue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tony/Desktop/Git/Intrigue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Intrigue

# Build rule for target.
Intrigue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Intrigue
.PHONY : Intrigue

# fast build rule for target.
Intrigue/fast:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/build
.PHONY : Intrigue/fast

decrypt.o: decrypt.cpp.o

.PHONY : decrypt.o

# target to build an object file
decrypt.cpp.o:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/decrypt.cpp.o
.PHONY : decrypt.cpp.o

decrypt.i: decrypt.cpp.i

.PHONY : decrypt.i

# target to preprocess a source file
decrypt.cpp.i:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/decrypt.cpp.i
.PHONY : decrypt.cpp.i

decrypt.s: decrypt.cpp.s

.PHONY : decrypt.s

# target to generate assembly for a file
decrypt.cpp.s:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/decrypt.cpp.s
.PHONY : decrypt.cpp.s

encrypt.o: encrypt.cpp.o

.PHONY : encrypt.o

# target to build an object file
encrypt.cpp.o:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/encrypt.cpp.o
.PHONY : encrypt.cpp.o

encrypt.i: encrypt.cpp.i

.PHONY : encrypt.i

# target to preprocess a source file
encrypt.cpp.i:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/encrypt.cpp.i
.PHONY : encrypt.cpp.i

encrypt.s: encrypt.cpp.s

.PHONY : encrypt.s

# target to generate assembly for a file
encrypt.cpp.s:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/encrypt.cpp.s
.PHONY : encrypt.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Intrigue.dir/build.make CMakeFiles/Intrigue.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Intrigue"
	@echo "... decrypt.o"
	@echo "... decrypt.i"
	@echo "... decrypt.s"
	@echo "... encrypt.o"
	@echo "... encrypt.i"
	@echo "... encrypt.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

